# Pandas DataFrame 

This section covers everything about Pandas DataFrames.

A DataFrame is a 2D labeled data structure with rows and columns.

In [29]:
import pandas as pd
import numpy as np

## What is a DataFrame?

A DataFrame:
- is two-dimensional (rows and columns)
- has labeled columns and index
- can store different data types

Think of it like an Excel sheet.

In [30]:
data={
    'Name': ['Ahmad', 'Ali', 'Zain', 'John'],
    'Age' : [20, 18, 21, 22],
    'City' : ['Lahore', 'Karachi', 'Faisalabad', 'Newyork'],
    'Field':['BSAI', 'BSCS', 'BSDS', 'BSCS']
}

df=pd.DataFrame(data)
df

    Name  Age        City Field
0  Ahmad   20      Lahore  BSAI
1    Ali   18     Karachi  BSCS
2   Zain   21  Faisalabad  BSDS
3   John   22     Newyork  BSCS

## Creating DataFrame from List of Dictionaries

In [31]:
data= [
    {'Name': 'Ahmad', 'Age': 20, 'Roll number': 37},
    {'Name': 'Ali', 'Age': 19, 'Roll number': 40}
]
df=pd.DataFrame(data)
df

    Name  Age  Roll number
0  Ahmad   20           37
1    Ali   19           40

## Custom Index

In [32]:
df.index=['Student 1', 'Student 2']
print(df)

            Name  Age  Roll number
Student 1  Ahmad   20           37
Student 2    Ali   19           40

## DataFrame Structure

In [33]:
print(df.shape)
print(df.columns)
print(df.index)
print(df.dtypes)

(2, 3)
Index(['Name', 'Age', 'Roll number'], dtype='object')
Index(['Student 1', 'Student 2'], dtype='object')
Name           object
Age             int64
Roll number     int64
dtype: object

In [34]:
df.head()

            Name  Age  Roll number
Student 1  Ahmad   20           37
Student 2    Ali   19           40

## Selecting Columns

In [35]:
df['Name']         # Series
df[['Name', 'Age']]    # DataFrame

            Name  Age
Student 1  Ahmad   20
Student 2    Ali   19

## Selecting Rows

In [ ]:
df.loc['Student 1'] #by label

Name           Ahmad
Age               20
Roll number       37
Name: Student 1, dtype: object

In [39]:
df.iloc[1]

Name           Ali
Age             19
Roll number     40
Name: Student 2, dtype: object

In [40]:
df.iloc[0:1]

            Name  Age  Roll number
Student 1  Ahmad   20           37

In [41]:
df.loc['Student 1', 'Name']

'Ahmad'

In [ ]:
df['Roll number']=[42,44]  #updateing roll number values
df

            Name  Age  Roll number
Student 1  Ahmad   20           42
Student 2    Ali   19           44

In [ ]:
df['Age']=df['Age']+1    # Modifying Column
df

            Name  Age  Roll number
Student 1  Ahmad   22           42
Student 2    Ali   21           44

## Deleting Column

In [48]:
df.drop('Age', axis=1)

            Name  Roll number
Student 1  Ahmad           42
Student 2    Ali           44

## Filtering Data

In [51]:
df[df['Age']>21]

            Name  Age  Roll number
Student 1  Ahmad   22           42

In [ ]:
df.info()